# Generated by Django 3.2.8 on 2021-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_moments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='photo',
            field=models.ImageField(upload_to='moments/media'),
        ),
        migrations.AlterField(
            model_name='moments',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
